# Generated by Django 2.1.2 on 2018-11-05 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_map', '0002_auto_20181016_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chunk',
            old_name='road_nodes',
            new_name='roads',
        ),
    ]
