# Generated by Django 2.1.2 on 2018-11-14 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player_manager', '0003_auto_20181017_1610'),
        ('game_map', '0003_auto_20181105_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('taken_over', models.BooleanField(default=False)),
                ('tier', models.IntegerField(default=1)),
                ('resource_type', models.IntegerField(choices=[(1, 'Resource 1'), (2, 'Resource 2'), (3, 'Resource 3')])),
                ('resources_left', models.FloatField(default=100)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_map.Chunk')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='player_manager.Player')),
            ],
        ),
    ]
