# Generated by Django 2.1.2 on 2018-12-16 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guild_manager', '0001_initial'),
        ('game_map', '0006_auto_20181114_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='owner_guild',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='guild_manager.Guild'),
        ),
        migrations.AddField(
            model_name='structure',
            name='taken_over_by_guild',
            field=models.BooleanField(default=False),
        ),
    ]
