# Generated by Django 2.1.2 on 2019-01-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_map', '0007_auto_20181216_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='resource_type',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)]),
        ),
    ]
