# Generated by Django 2.1.2 on 2019-01-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_map', '0008_auto_20190110_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='rotation',
            field=models.FloatField(default=0),
        ),
    ]
