# Generated by Django 2.1.2 on 2019-01-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_map', '0009_structure_rotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='resource_type',
            field=models.IntegerField(choices=[(1, 'Cementia'), (2, 'Plasmatia'), (3, 'Auferia'), (4, 'AoE Buff')]),
        ),
    ]
