# Generated by Django 2.1.2 on 2018-12-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_name', models.TextField()),
                ('Cementia', models.FloatField(default=0.0)),
                ('Plasmatia', models.FloatField(default=0.0)),
                ('Auferia', models.FloatField(default=0.0)),
            ],
        ),
    ]
