# Generated by Django 2.1.2 on 2019-01-25 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player_manager', '0007_auto_20190120_1841'),
        ('guild_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuildInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guild_manager.Guild')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_manager.Player')),
            ],
        ),
    ]
