# Generated by Django 2.1.2 on 2019-02-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild_manager', '0002_guildinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='color',
            field=models.TextField(default='#C62828'),
        ),
        migrations.AddField(
            model_name='guild',
            name='icon',
            field=models.CharField(choices=[('c', 'Circle'), ('s', 'Square'), ('t', 'Triangle')], default='c', max_length=1),
        ),
    ]
