# Connection specific
SERVER_URL = "filipplotnicki.com:8000/ws/"


# Map specific
CHUNK_SIZE = 0.01


# Client-driven message types
MESSAGE_TYPE_AUTH_EVENT = 0
MESSAGE_TYPE_LOCATION_EVENT = 1
MESSAGE_TYPE_CHUNK_REQUEST = 2
MESSAGE_TYPE_DYNAMIC_CHUNK_DATA_REQUEST = 3
MESSAGE_TYPE_STRUCT_TAKEOVER_REQUEST = 4

# Server-driven (also referred to as special) message types
SPECIAL_MESSAGE_MAP_UPDATE = 0
SPECIAL_MESSAGE_NOTIFICATION = 1

# Resource types

RESOURCE_TYPE_1 = 1
RESOURCE_TYPE_2 = 2
RESOURCE_TYPE_3 = 3

# Resource types but with names
RESOURCE_CEMENTIA = 1
RESOURCE_PLASMATIA = 2
RESOURCE_AUFERIA = 3


# GUILD_ACTION_TYPES
GUILD_ACTION_CREATE_GUILD = 1