# Generated by Django 2.1.2 on 2018-10-17 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activeplayer',
            old_name='account',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='account',
            new_name='user',
        ),
    ]
