# Generated by Django 2.1.2 on 2018-10-17 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player_manager', '0002_auto_20181017_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeplayer',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='activeplayer',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='activeplayer',
            name='on_which_chunk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game_map.Chunk'),
        ),
    ]
