# Generated by Django 2.1.2 on 2018-11-14 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_manager', '0003_auto_20181017_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeplayer',
            name='on_which_chunk',
        ),
    ]
