# Generated by Django 2.1.2 on 2018-12-16 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guild_manager', '0001_initial'),
        ('player_manager', '0004_remove_activeplayer_on_which_chunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='guild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guild_manager.Guild'),
        ),
    ]
