# Generated by Django 2.1.2 on 2019-01-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_manager', '0005_player_guild'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeplayer',
            name='rotation',
            field=models.FloatField(null=True),
        ),
    ]
