# Generated by Django 2.1.2 on 2019-01-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_manager', '0006_activeplayer_rotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Auferia',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='Cementia',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='Plasmatia',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='exp',
            field=models.IntegerField(default=0),
        ),
    ]
