version: '3'

services:
  db:
    image: postgres
    volumes:
    - ../postgres-data:/var/lib/postgresql/data
  web:
    #env_file:
    #- ./web-variables.env
    image: city-game-development-image
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000  --noreload
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

